### ISSUE TITLE
Create ortholog information icons

### ISSUE THREAD

**Issue by khybiske** [SuLab/ChlamBase.org#77]
In Orthologs module, create columns to display colored icons depicting: 
Expression data
GO annotations
Operon data
Mutants
H-P intx

Show these for each checked strain

**Comment by djow2019** [comment]
What do you think of this?
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/cab3c478-ccc2-4685-9a6d-9c1663ba31bd)

@andrewsu @putmantime I ended up querying all the data for each ortholog because I wasn't sure how else to check if the data existed. Is there a better way to do this?

**Comment by khybiske** [comment]
@djow2019 I like it. Only suggestion is to add 'Mutants' as a category. To make room, you can delete 'Operon data' (that will be x for all genes right now). 

I can't answer your querying question, but the logic sounds right to me. ;)

**Comment by djow2019** [comment]
All done.
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/6875858b-425a-45aa-a012-7fad6d55fd4f)
